ROUND_NAMES = ["I","II"]
EXAM_TYPES = ["MHCET","AIEEE"]
MARK_TYPES = ["Rank","Score"]


U_ROUND="HOME UNIV. ROUND"
SHIFT="SHIFT"
AIEEE_RANK="AIEEE RANK"
AIEEE_SCORE="AIEEE SCORE"

OPEN_MALE_SCORE="OPEN (MALE) Score"
OPEN_FEMALE_SCORE="OPEN (FEMALE) Score"
OPEN_MALE_SML="OPEN (MALE) SML"
OPEN_FEMALE_SML="OPEN (FEMALE) SML"

SC_MALE_SCORE="SC (MALE) Score"
SC_FEMALE_SCORE="SC (FEMALE) Score"
SC_MALE_SML="SC (MALE) SML"
SC_FEMALE_SML="SC (FEMALE) SML"

ST_MALE_SCORE="ST (MALE) Score"
ST_FEMALE_SCORE="ST (FEMALE) Score"
ST_MALE_SML="ST (MALE) SML"
ST_FEMALE_SML="ST (FEMALE) SML"

VJ_MALE_SCORE="VJ (MALE) Score"
VJ_FEMALE_SCORE="VJ (FEMALE) Score"
VJ_MALE_SML="VJ (MALE) SML"
VJ_FEMALE_SML="VJ (FEMALE) SML"

NT1_MALE_SCORE="NT1 (MALE) Score"
NT1_FEMALE_SCORE="NT1 (FEMALE) Score"
NT1_MALE_SML="NT1 (MALE) SML"
NT1_FEMALE_SML="NT1 (FEMALE) SML"

NT2_MALE_SCORE="NT2 (MALE) Score"
NT2_FEMALE_SCORE="NT2 (FEMALE) Score"
NT2_MALE_SML="NT2 (MALE) SML"
NT2_FEMALE_SML="NT2 (FEMALE) SML"

NT3_MALE_SCORE="NT3 (MALE) Score"
NT3_FEMALE_SCORE="NT3 (FEMALE) Score"
NT3_MALE_SML="NT3 (MALE) SML"
NT3_FEMALE_SML="NT3 (FEMALE) SML"

OBC_MALE_SCORE="OBC (MALE) Score"
OBC_FEMALE_SCORE="OBC (FEMALE) Score"
OBC_MALE_SML="OBC (MALE) SML"
OBC_FEMALE_SML="OBC (FEMALE) SML"
